OUTPUT_DIR: '/data/jsliao/DNN_A'
WORKERS: 4
PRINT_FREQ: 1
AMP:
  ENABLED: False

MODEL:
  NAME: DNN_A
  NUM_CLASSES_ORDER_DISORDER: 2
  NUM_CLASSES_MOL:  #number of compound classes, only work in DNN-CP
AUG:
  TIMM_AUG:
    USE_LOADER: False
LOSS:
  LABEL_SMOOTHING: 0.0
CUDNN:
  BENCHMARK: True
  DETERMINISTIC: False
  ENABLED: True
DATASET:
  ROOT: '/data/jsliao/MPDATASET'
  DATASET: 'cls_reg_exp'
  NUM_POINT: 500
  PROCESS_DATA: True
  USE_UNIFORM_SAMPLE: False
  USE_NORMALS: True
TEST:
  BATCH_SIZE_PER_GPU: 16
TRAIN:
  BATCH_SIZE_PER_GPU: 16
  LR: 0.001
  BEGIN_EPOCH: 0
  END_EPOCH: 1000
  LR_SCHEDULER:
    METHOD: 'MultiStep'
    MILESTONES : [200, 700, 900, 910, 920, 930, 940, 950, 960, 970, 980, 990]
    GAMMA : 0.5
  OPTIMIZER: sgd
  MOMENTUM: 0.0009
  NESTEROV: True
  WD: 0.001
  WITHOUT_WD_LIST: ['bn', 'bias', 'ln']
  SHUFFLE: True
DEBUG:
  DEBUG: False